(require sicp)

;;; Exercise 1.15.
;;;
;;; The sine of an angle (specified in radians) can be computed by
;;; making use of the approximation sin x x if x is sufficiently small,
;;; and the trigonometric identity
;;;
;;; sin(x) = 3sin(x/3) - 4sin^3(x/3)
;;;
;;; to reduce the size of the argument of sin. (For purposes of this
;;; exercise an angle is considered ``sufficiently small'' if its
;;; magnitude is not greater than 0.1 radians.) These ideas are
;;; incorporated in the following procedures:
;;;
;;; (define (cube x) (* x x x))
;;; (define (p x) (- (* 3 x) (* 4 (cube x))))
;;; (define (sine angle)
;;;    (if (not (> (abs angle) 0.1))
;;;        angle
;;;        (p (sine (/ angle 3.0)))))
;;;
;;; a.  How many times is the procedure p applied when (sine 12.15) is
;;; evaluated?
;;;
;;; b.  What is the order of growth in space and number of steps (as a
;;; function of angle) used by the process generated by the sine procedure
;;; when (sine angle) is evaluated?


;;; Solution (a) -- Use substitution to expand the evaluation.

(sine 12.15)
(p (sine (/ 12.15 3.0)))
(p (sine 4.05))
(p (p (sine (/ 4.05 3.0))))
(p (p (sine 1.35)))
(p (p (p (sine (/ 1.35 3.0)))))
(p (p (p (sine 0.45))))
(p (p (p (p (sine (/ 0.45 3.0))))))
(p (p (p (p (sine 0.15)))))
(p (p (p (p (p (sine (/ 0.15 3.0)))))))
(p (p (p (p (p (sine 0.05))))))
(p (p (p (p (p 0.05))))) ; p is evaluated five times

;;; Solution (b)
;;; The procedure must continue dividing by 3.0 until
;;; the input value is small enough.

;;; Every needed division by 3.0 increases the number of
;;; steps by a factor. So the computational resources
;;; required O(n) increases proportionally to log base 3.

;;; θ(a) = k log_3(a)
;;; θ(3a)  = k log_3(3a)  = k log_3(3)  + k log_3(a) =  k + θ(a)
;;; θ(9a)  = k log_3(9a)  = k log_3(9)  + k log_3(a) = 2k + θ(a)
;;; θ(27a) = k log_3(27a) = k log_3(27) + k log_3(a) = 3k + θ(a)
;;; etc.
